<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;

class RestauranteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbrestaurante')->insert(
            array(
                [
                    'nomeRestaurante' => "Ragazzo",
                    'cnpjRestaurante' => "05792297000199",
                    'telRestaurante' => "3003-3838",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "ragazzo@contato.com",
                    'cepRestaurante' => "08410000",
                    'ruaRestaurante' => " R. Salvador Gianetti",
                    'numRestaurante' => " 900",
                    'bairroRestaurante' => "Guaianases",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 45,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 1,
                    'horarioAberturaRestaurante' => "08:00:00",
                    'horarioFechamentoRestaurante' => "22:00:00",
                    'descricaoRestaurante' => "Ragazzo é um restaurante italiano que oferece uma experiência gastronômica única, com pratos que vão desde a culinária tradicional italiana até as mais modernas criações. O restaurante é um dos mais tradicionais da cidade, com mais de 20 anos de história e uma equipe de profissionais altamente qualificados. O ambiente é aconchegante e agradável, com uma decoração que remete à Itália, e a música ambiente é sempre apropriada para o momento. O restaurante é ideal para quem busca um ambiente agradável e uma experiência gastronômica única.",
                    'created_at' => '2022-08-10 21:46:28',
                    'updated_at' => '2022-08-10 21:46:28',
                ],
                [
                    'nomeRestaurante' => "Spoleto",
                    'cnpjRestaurante' => "98765432109876",
                    'telRestaurante' => "11 2176-3457",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "spoleto@contato.com",
                    'cepRestaurante' => "08461110",
                    'ruaRestaurante' => "Shopping Metro Itaquera",
                    'numRestaurante' => "268",
                    'bairroRestaurante' => "Itaquera",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 50,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 4,
                    'horarioAberturaRestaurante' => "10:00:00",
                    'horarioFechamentoRestaurante' => "23:00:00",
                    'descricaoRestaurante' => "Spoleto é um restaurante italiano que oferece uma experiência gastronômica única, com pratos que vão desde a culinária tradicional italiana até as mais modernas criações. O restaurante é um dos mais tradicionais da cidade, com mais de 20 anos de história e uma equipe de profissionais altamente qualificados. O ambiente é aconchegante e agradável, com uma decoração que remete à Itália, e a música ambiente é sempre apropriada para o momento. O restaurante é ideal para quem busca um ambiente agradável e uma experiência gastronômica única.",
                    'created_at' => '2022-09-10 21:46:28',
                    'updated_at' => '2022-09-10 21:46:28',
                ],
                [
                    'nomeRestaurante' => "Bar Monica & Baixinho",
                    'cnpjRestaurante' => "81920628000107",
                    'telRestaurante' => "11 98684-2893",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "restaurantemonica@contato.net",
                    'cepRestaurante' => "08421550",
                    'ruaRestaurante' => " R. Coração Sertanejo",
                    'numRestaurante' => "509",
                    'bairroRestaurante' => "COHAB Fazenda do Carmo",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 30,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 5,
                    'horarioAberturaRestaurante' => "11:30:00",
                    'horarioFechamentoRestaurante' => "22:00:00",
                    "descricaoRestaurante" => "Monica & baixinhos é um estabelecimento que busca oferecer as melhores pizzas da região por preços acessíveis.",
                    'created_at' => '2022-09-10 21:46:28',
                    'updated_at' => '2022-09-10 21:46:28',
                ],

                [
                    'nomeRestaurante' => "Pizzaria Morcego",
                    'cnpjRestaurante' => "88522519000180",
                    'telRestaurante' => "11 2555-3521",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "pizzariamorcego@outlook.com",
                    'cepRestaurante' => "08421490",
                    'ruaRestaurante' => " R. Renato Russo",
                    'numRestaurante' => "05",
                    'bairroRestaurante' => "COHAB Fazenda do Carmo",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 20,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 8,
                    'horarioAberturaRestaurante' => "8:00:00",
                    'horarioFechamentoRestaurante' => "17:00:00",
                    'descricaoRestaurante' => "Pizzaria do morcego, uma das melhores da região com ótimo atendimento ao seus clientes.",
                    'created_at' => Date::now(),
                    'updated_at' => Date::now(),
                ],
                [
                    'nomeRestaurante' => "Habib's Guaianases",
                    'cnpjRestaurante' => "64340136000123",
                    'telRestaurante' => "11 2016-8436",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "habibs.guaianases@outlook.com",
                    'cepRestaurante' => "08451000",
                    'ruaRestaurante' => "Estr. do Lageado Velho",
                    'numRestaurante' => "987",
                    'bairroRestaurante' => "Guaianases",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 40,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 2,
                    'horarioAberturaRestaurante' => "11:00:00",
                    'horarioFechamentoRestaurante' => "23:00:00",
                    'descricaoRestaurante' => "Rede de fast-food árabe, popular pelas esfihas, tem um ambiente simples e informal também para grandes grupos.",
                    'created_at' => Date::now(),
                    'updated_at' => Date::now(),
                ],
                [
                    'nomeRestaurante' => "James Café & Bistrô",
                    'cnpjRestaurante' => "04040993000186",
                    'telRestaurante' => "11 2495-6880",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "jamesbistro@outlook.com",
                    'cepRestaurante' => "08210150",
                    'ruaRestaurante' => "Rua Dudu",
                    'numRestaurante' => "182",
                    'bairroRestaurante' => "Itaquera",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 35,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 1,
                    'horarioAberturaRestaurante' => "09:00:00",
                    'horarioFechamentoRestaurante' => "18:00:00",
                    'descricaoRestaurante' => "James café, o mehor cafe da região",
                    'created_at' => Date::now(),
                    'updated_at' => Date::now(),
                ],
                [
                    'nomeRestaurante' => "Buffet JK",
                    'cnpjRestaurante' => "41760837000116",
                    'telRestaurante' => "11 95765-1968",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "jkbuffet@outlook.com",
                    'cepRestaurante' => "08421570",
                    'ruaRestaurante' => "Rua Saturnino Pereira",
                    'numRestaurante' => "110",
                    'bairroRestaurante' => "Guaianases",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 100,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 4,
                    'horarioAberturaRestaurante' => "10:00:00",
                    'horarioFechamentoRestaurante' => "00:00:00",
                    'descricaoRestaurante' => "O melhor buffet da região com o melhor ambiente.",
                    'created_at' => Date::now(),
                    'updated_at' => Date::now(),
                ],

                [
                    'nomeRestaurante' => "Pop Esfirra",
                    'cnpjRestaurante' => "44435543000107",
                    'telRestaurante' => "11 2297-7034",
                    'senhaRestaurante' => password_hash('123', PASSWORD_DEFAULT),
                    'fotoRestaurante' => "user.png",
                    'emailRestaurante' => "popesfirra@outlook.com",
                    'cepRestaurante' => "08010090",
                    'ruaRestaurante' => "Avenida Marechal Tito",
                    'numRestaurante' => "294",
                    'bairroRestaurante' => " São Miguel Paulista",
                    'cidadeRestaurante' => "São Paulo",
                    'estadoRestaurante' => "SP",
                    'capacidadeRestaurante' => 50,
                    'lotacaoRestaurante' => false,
                    'idTipoRestaurante' => 9,
                    'horarioAberturaRestaurante' => "09:00:00",
                    'horarioFechamentoRestaurante' => "22:00:00",
                    'descricaoRestaurante' => "A melhor Esfiharia da região com a melhor qualidade.",
                    'created_at' => Date::now(),
                    'updated_at' => Date::now(),
                ]
            )
        );
    }
}
